### ISSUE TITLE
permission denied issue?

### ISSUE THREAD

**Issue by hrstoyanov** [amarao/ansible-flyway#6]
```
TASK: [george.shuklin.flyway | Creating directory for flyway] ***************** 
<localhost> REMOTE_MODULE file path=/opt/flyway state=directory
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1446709118.81-87692608641197 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1446709118.81-87692608641197 && echo $HOME/.ansible/tmp/ansible-tmp-1446709118.81-87692608641197']
<localhost> PUT /tmp/tmpx83LyY TO /home/hristo/.ansible/tmp/ansible-tmp-1446709118.81-87692608641197/file
<localhost> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /home/hristo/.ansible/tmp/ansible-tmp-1446709118.81-87692608641197/file; rm -rf /home/hristo/.ansible/tmp/ansible-tmp-1446709118.81-87692608641197/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/hristo/.ansible/tmp/ansible-tmp-1446709118.81-87692608641197/file", line 2012, in <module>
    main()
  File "/home/hristo/.ansible/tmp/ansible-tmp-1446709118.81-87692608641197/file", line 279, in main
    os.mkdir(curpath)
OSError: [Errno 13] Permission denied: '/opt/flyway'


FATAL: all hosts have already failed -- aborting

```

**Comment by amarao** [comment]
Hello.
Permission was denied. You have no permission to configure that host. Please contact system administrator to gain elevated privileges.
